### PR TITLE
Typo in circle.yml

### PR DESCRIPTION
**Pull request by D34THWINGS**

### CODE REVIEW

**Comment by bahmutov** [comment]
hmm, there wasn't one, I have just added it

**Comment by jennifer-shehane** [comment]
@D34THWINGS Thanks for the contribution! Could you please sign our CLA?

**Comment by D34THWINGS** [comment]
@jennifer-shehane Done! Sorry I forgot it :(

**Comment by jennifer-shehane** [comment]
@D34THWINGS No worries! It was on us, it usually automatically asks, but it didn't this time. 😄

**Comment by bahmutov** [comment]
hey @D34THWINGS thanks for noticing and fixing this - this issue is no longer relevant, since we moved to use CircleCI orbs, take a look https://github.com/cypress-io/cypress-example-kitchensink/blob/master/circle.yml

**Pull request closed without merging**
