### PR TITLE
Delete shippable.yml

### PR DESCRIPTION
**Pull request by mikedlr**
Shippable CU was bought by Jfrog and closed down.

### CODE REVIEW

**Comment by mikedlr** [comment]
This is only a deletion - no copyright material so no need for CLA / "this is not a contribution".

**Comment by MikeMcC399** [comment]
@mikedlr 

- Before deleting [shippable.yml](https://github.com/cypress-io/cypress-example-kitchensink/blob/master/shippable.yml) from this repository, the reference to the file in https://github.com/cypress-io/cypress-documentation/blob/main/docs/guides/continuous-integration/ci-provider-examples.mdx first needs to be removed.

- I have submitted a related PR https://github.com/cypress-io/cypress-example-kitchensink/pull/601

**Comment by MikeMcC399** [comment]
@mikedlr 

Were you previously using Shippable and did you migrate to JFrog?

**Comment by MikeMcC399** [comment]
@mikedlr 

I hope you don't mind, but in order not to hold up the resolution of this issue I have resubmitted the deletion of [shippable.yml](https://github.com/cypress-io/cypress-example-kitchensink/blob/master/shippable.yml) in a separate PR https://github.com/cypress-io/cypress-example-kitchensink/pull/603 as one of several PRs necessary to cleanly remove Shippable.

I would still be interested to hear back if you have any experience with a migration to JFrog.

This PR can be closed now.

**Comment by mikedlr** [comment]
@MikeMcC399 that's greatly appreciated.

**Pull request closed without merging**
