### PR TITLE
🚀 publish video and screenshots as CI artifact in azure-ci

### PR DESCRIPTION
**Pull request by ali4heydari**

### CODE REVIEW

**Review by bahmutov — APPROVED** [review]
seems good

**Review by bahmutov — CHANGES_REQUESTED** [review]
@ali4heydari did you see the AzureCI failures? 
Screen Shot 2020-11-03 at 3 15 02 PM

**Comment by ali4heydari** [comment]
Yes, I saw it now. I will try to solve the problem soon. I think it's because of parallel jobs. Because I did the same thing on a job in my own repository and it was successful.

**Comment by jennifer-shehane** [comment]
closing as stale. Feel free to reopen a PR to address the issue.

**Pull request closed without merging**
