### PR TITLE
Heroku ci 🎉 142

### LINKED ISSUE #142: Set up Heroku CI example
https://devcenter.heroku.com/articles/heroku-ci
https://devcenter.heroku.com/articles/heroku-ci-technical-detail-on-ci-lifecycle

### PR DESCRIPTION
**Pull request by bahmutov**
- closes #142 
- Heroku run: https://dashboard.heroku.com/pipelines/6ab6956d-1ea8-41ea-a11d-45b8a2a64447/tests/12
- Dashboard recording: https://dashboard.cypress.io/#/projects/4b7344/runs/3092

## note
- need to put `PORT=808` into config environment variables
- also need to put `CYPRESS_CACHE_FOLDER=cache/Cypress` into environment variables so `npm install` puts binary into `node_modules`, BUT when running tests need to overwrite it on the command like with `CYPRESS_CACHE_FOLDER=./node_modules/cypress/cache/Cypress npm run test:ci:record` which is weir

- dashboard is missing information, but there are some Heroku environment variables defined see https://devcenter.heroku.com/articles/heroku-ci#immutable-environment-variables

```
The following environment variables are available in all Heroku CI test runs and cannot be changed:

CI: A string indicating that this is a continuous integration environment. This value is always true.
HEROKU_TEST_RUN_BRANCH: A string representing the branch of the commit being tested.
HEROKU_TEST_RUN_COMMIT_VERSION: A string representing the commit version being tested (this is usually the commit’s SHA).
HEROKU_TEST_RUN_ID: A string UUID representing the unique ID of the test run.
```

- could not find any Heroku CI badges to add to README

### CODE REVIEW

**Comment by dauledk** [comment]
Hi @bahmutov, thanks for looking into Heroku CI. I have some follow up questions, on the different notes:

- The port 8080, is that in `cypress.json` or heroku dashboard env?
- The `CYPRESS_CACHE_FOLDER=cache/Cypress` is that heroku dashboard env? And where in code do you set `CYPRESS_CACHE_FOLDER=./node_modules/cypress/cache/Cypress npm run test:ci:record` before running tests?

Thanks for the help

**Comment by bahmutov** [comment]
@dauledk 

- when heroku ci runs it seems it allocates random port and sets environment variable `PORT` which our server then picks up - but the tests assume `localhost:8080` and thus break. By setting explicit port we force the server and the tests to agree.
- yes, the environment variable in Heroku CI settings sets `CYPRESS_CACHE_FOLDER=cache/Cypress` and it controls where Cypress binary is installed into (into `node_modules` to be cached by Heroku). But when we run Cypress we unfortunately have to set  `CYPRESS_CACHE_FOLDER=./node_modules/cypress/cache/Cypress` for Cypress NPM package to correctly find the same binary inside `node_modules`. I have opened an issue in https://github.com/cypress-io/cypress/issues/2634 to fix the difference and only use the same environment variable to store binary in `node_modules`

**Comment by dauledk** [comment]
Thanks - I just looked at the code to this PR, and it makes more sense now. However I noticed the usage of `cedar-14` stack, any specific reason for this deprecated stack? It reaches end of life April next year.

**Comment by bahmutov** [comment]
Yes it is weird but I had a Heroku CI error thrown when trying to use modern stack, so it remains to be seen why this is needed

**Comment by dauledk** [comment]
The cache is working, but unzipping still takes a long time, 1 minute and 32 seconds. Any way to improve the speed?

This is a screenshot from the build process:

screenshot 2018-10-26 at 14 41 29

**Comment by bahmutov** [comment]
But it should just unzip once and then the binary is cached right?

**Pull request merged**
