### PR TITLE
ci: migrate github action workflows to ubuntu-24.04

### PR DESCRIPTION
**Pull request by MikeMcC399**
## Issue

The GitHub runner image [ubuntu-24.04](https://github.com/actions/runner-images/blob/main/images/ubuntu/Ubuntu2404-Readme.md) is replacing [ubuntu-22.04](https://github.com/actions/runner-images/blob/main/images/ubuntu/Ubuntu2204-Readme.md) as `latest` image.

## Change

Migrate GitHub Actions workflows to [ubuntu-24.04](https://github.com/actions/runner-images/blob/main/images/ubuntu/Ubuntu2404-Readme.md).

Affected workflows:

- [.github/workflows/chrome-docker.yml](https://github.com/cypress-io/cypress-example-kitchensink/blob/master/.github/workflows/chrome-docker.yml)
- [.github/workflows/chrome.yml](https://github.com/cypress-io/cypress-example-kitchensink/blob/master/.github/workflows/chrome.yml)
- [.github/workflows/parallel.yml](https://github.com/cypress-io/cypress-example-kitchensink/blob/master/.github/workflows/parallel.yml)
- [.github/workflows/single.yml](https://github.com/cypress-io/cypress-example-kitchensink/blob/master/.github/workflows/single.yml)
- [.github/workflows/using-action.yml](https://github.com/cypress-io/cypress-example-kitchensink/blob/master/.github/workflows/using-action.yml)

### CODE REVIEW

**Comment by MikeMcC399** [comment]
Leave in draft state until [ubuntu-24.04](https://github.com/actions/runner-images/blob/main/images/ubuntu/Ubuntu2404-Readme.md) officially exits beta status as shown on [Available Images](https://github.com/actions/runner-images/blob/main/README.md#available-images).

**Comment by MikeMcC399** [comment]
[ubuntu-24.04](https://github.com/actions/runner-images/blob/main/images/ubuntu/Ubuntu2404-Readme.md) has officially transferred from beta to GA status as shown on [Available Images](https://github.com/actions/runner-images/blob/main/README.md#available-images). The `beta` label has been removed.

**Comment by MikeMcC399** [comment]
@jennifer-shehane 

This one is also awaiting review and merge, when convenient for you.

**Review by jennifer-shehane — APPROVED** [review]
Yah some of these PRs went under my radar at some point. Thanks as always!

**Pull request merged**
