### PR TITLE
address #23 add example of 'select' option

### PR DESCRIPTION
**Pull request by jeremybowden73**
Addresses issue #23: add example of 'select' option.

### CODE REVIEW

**Comment by jennifer-shehane** [comment]
@bahmutov I can't even figure out how to rerun these Shippable builds, do I have the correct permissions? 

Also - the Travis run doesn't seem to be skipping recording on external PRs.

**Comment by bahmutov** [comment]
Hmm, why are the versions in this PR so old - Travis is showing
```
$ node --version
v6.5.0
$ npm --version
3.10.3
It looks like this is your first time using Cypress: 2.1.0
```
Let me see what is going on

**Comment by bahmutov** [comment]
@jeremybowden73 can I ask you to disable any kind of formatting in your text editor? I am looking at the changes in app/commands/actions.html and there are a lot of white space changes that seem unnecessary. Can you also pull the latest code from `master` into your branch?

The shippable and other test failures are flukes, other CIs pass without a problem.

**Comment by jeremybowden73** [comment]
@bahmutov I've pulled the latest code from master, and removed all the white space changes that you mentioned.

**Comment by bahmutov** [comment]
@jeremybowden73 I have added similar assertions in https://github.com/cypress-io/cypress-example-kitchensink/pull/349 will close your pull request - thank you for taking time to do this, really helpful

**Pull request closed without merging**
