### PR TITLE
build: add scripts to Docker build

### PR DESCRIPTION
**Pull request by sebastianscinteie**
Scripts folder needed when creating a docker image with "docker build". If the folder is not copied, then "RUN npm ci" will throw the following error: 
"Error: Cannot find module '/home/node/app/scripts/prepare.js'"

### CODE REVIEW

**Comment by sebastianscinteie** [comment]
@MikeMcC399 Fixed the issue with Semantic PR, had to also rename the commit.
For the other docker file you mentioned I just copy and pasted the contents from the one in root.
I'm not sure why there are two ci checks still failing.

**Comment by MikeMcC399** [comment]
@sebastianscinteie 

Thanks for making the changes! The other CI issues are not related to this PR and will need to be separately investigated if they persist.

I noticed that
`docker build`
failed using Node.js `18` and it seems this is due to the removal of `npm bin` in `npm 9.0.0`.

Please consider fixing this issue also in this PR, so that the Docker files are compatible with being built on Node.js `16`, `18` and `20`.

- I have also submitted a documentation issue https://github.com/cypress-io/cypress-documentation/issues/5381

**Comment by sebastianscinteie** [comment]
@MikeMcC399 replaced npm bin with npx

**Comment by MikeMcC399** [comment]
LGTM!

I was able to run from Node.js `18.17.0` with:

```
docker build  -t kitchensink .
docker run -it kitchensink
npm run local:run
```

CI is still having an unrelated problem though.

**Review by jaffrepaul — APPROVED** [review]

**Comment by nagash77** [comment]
I am seeing two failing tests in CircleCI.  I don't have time at the moment to dig in though.

**Comment by MikeMcC399** [comment]
@nagash77 

> I am seeing two failing tests in CircleCI. I don't have time at the moment to dig in though.

- I found a CircleCI issue for this: https://github.com/CircleCI-Public/browser-tools-orb/issues/75

Perhaps you could check if a new release of https://github.com/cypress-io/circleci-orb is needed to pull in the solution or if it will get automatically used?

**Comment by MikeMcC399** [comment]
- The issue CircleCI issue has also been reported to https://github.com/cypress-io/circleci-orb/issues/434

**Comment by nagash77** [comment]
I am not super familiar with the code in the circleci repo, but I opened a PR here with a version bump that I think will solve this problem - https://github.com/cypress-io/circleci-orb/pull/435.  I am waiting on some internally reviews from folks that know that code base better than I do before I can confidently say this fixes the problem.

**Comment by MikeMcC399** [comment]
@nagash77 

> I am not super familiar with the code in the circleci repo, but I opened a PR here with a version bump that I think will solve this problem - [cypress-io/circleci-orb#435](https://github.com/cypress-io/circleci-orb/pull/435). I am waiting on some internally reviews from folks that know that code base better than I do before I can confidently say this fixes the problem.

I'm not at all familiar with the CircleCI code, but it seems like there would need to be a new release of `circleci-orb` and that release would have to be used here in this repo, which currently refers explicitly to version `3.1.2`.

https://github.com/cypress-io/cypress-example-kitchensink/blob/d07fe7c9ddb0c90ea21aee649f5c7b035e3c12ca/.circleci/config.yml#L9-L11

**Comment by nagash77** [comment]
I just published [cypress/circlieci-orb v3.1.3](https://github.com/cypress-io/circleci-orb/releases/tag/v3.1.3) that should have the fix in it.  I will update this repo next.

**Comment by nagash77** [comment]
Waiting for [this PR](https://github.com/cypress-io/cypress-example-kitchensink/pull/709) build to finish and then I will merge.

**Review by mjhenkes — APPROVED** [review]

**Pull request merged**
