### PR TITLE
Update index.html

### PR DESCRIPTION
**Pull request by mguery**
#240 Update 404 links in "Utilities" section.

### CODE REVIEW

**Comment by jennifer-shehane** [comment]
@bahmutov What's up with Appveyor? Can I ignore this?

**Comment by bahmutov** [comment]
Cypress does not have forked pull request detection on AppVeyor CI, I have noticed this yesterday from this build and have opened an issue https://github.com/cypress-io/cypress/issues/4063

**Comment by bahmutov** [comment]
but yeah, this is fine

**Pull request merged**
